# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62cbada9902f15e7724ee461311e4d776961b739604883b470f6867e589c88cb60a858b3465a2e3517dc8718e9bec87ceda2aaea6886ef2afbeca442738c775e

test:
  secret_key_base: 6994e585f6871ee75ba08ce94e046ceb0439a033976187d451f31db8b397c214ab99af4422702ba42eb077b54ddc0654cb7542960eaf0d30e4cd92f5d3c52996

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
